### ISSUE TITLE
Installing add-ons fails

### ISSUE THREAD

**Issue by Remicade** [casperklein/homeassistant-addons#10]
Hi casperklein,

I am trying to setup the Ycast add-on.
When I copy the url: https://github.com/casperklein/homeassistant-addons
 and search for  it in the Home Assistant Add-on Store it comes up with an example of Frenck??? 
Is the link broken?

Maybe I just need a few more hints;)
Can you explane in a more step-by-step way?

I had Ycast working before so I know how to configure it, the installing bit in HA is quit hard for me.

Thanks in advance,
Paul

**Comment by casperklein** [comment]
In the add-on store, click the 3 dots in the upper right and select "Repositories". Paste the URL there and click add.

Then you should see the ycast addon and be able to install it.

**Comment by Remicade** [comment]
Hi casperklein,
That was my fault....Thanks for helping me out.
Other isseu is more HA I think.
the log:

Bookmarks:
  Rock Antenne: https://mp3channels.webradio.rockantenne.de/rockantenne
  SWR1 BW: https://liveradio.swr.de/sw282p3/swr1bw/play.mp3
 
2023-01-11 21:08:45 INFO: YCast (1.1.0) server starting
2023-01-11 21:08:45 DEBUG: Debug logging enabled
 * Serving Flask app "ycast.server" (lazy loading)
 * Environment: development
 * Debug mode: off
2023-01-11 21:08:45 INFO:  * Running on http://0.0.0.0:80/ (Press CTRL+C to quit)

I have to check this out.
I am running Odroid M1 with tweaked installation...

Thanks again!
Paul

**Comment by casperklein** [comment]
The log looks fine to me.

**Comment by Remicade** [comment]
Thanks casperklein,
I think that the "create a manual entry in your DNS server" is not correctly made in my modem.
For this I made a request in the Ycast issue tracker.
Do you have a hint?
Thanks again.
Paul

**Comment by casperklein** [comment]
As [mentioned](https://github.com/milaq/YCast/issues/125#issuecomment-1382154634), you can use a dedicated DNS server (pi-hole for example) for that.

If your modem does not give you an option to configure a custom DNS server, you have to configure it on the device that ycast uses. When you use pi-hole as HA addon for example, you have to enter the HA IP address as DNS server on your device.
