### ISSUE TITLE
No content visible without login 

### ISSUE THREAD

**Issue by benek984** [casperklein/homeassistant-addons#13]
**Add-on name**
Netbox

**Describe the feature you'd like**
1. possibility to hide everything before login in.

**Comment by casperklein** [comment]
> possibility to hide everything before login in.

This is nothing, that this addon can provide. You should request this feature in [netbox](https://github.com/netbox-community/netbox) directly.

**Comment by casperklein** [comment]
I thought you were requesting a new netbox feature. As it's already available, it should be no problem to make this configurable in the addon. I'll take a look in the next days.

**Comment by casperklein** [comment]
The feature is available in the latest addon version (3.5.1.1).
