### ISSUE TITLE
Use `addon_config` option in Netbox

### ISSUE THREAD

**Issue by saya6k** [casperklein/homeassistant-addons#14]
**Add-on name**
Netbox

**Describe the feature you'd like**
Use map addon-config option to place netbox config directory inside `/config/addons_config/netbox`

**Describe alternatives you've considered**
Option to define custom config directory.

**Additional context**
https://developers.home-assistant.io/blog/2023/11/06/public-addon-config/
https://developers.home-assistant.io/docs/add-ons/configuration/#add-on-advanced-options

**Comment by casperklein** [comment]
It's already on my todo list 👍

**Comment by casperklein** [comment]
May I ask what's your use case, do you need access to the complete netbox `configuration.py` file?

The configuration can already be [changed/extended](https://github.com/casperklein/homeassistant-addons/tree/master/netbox#plugins). It's not explicitly mentioned, but this can be used for anything and is not limited to plugins configuration. `config/netbox/configuration.py` is appended to netbox's `configuration.py`.

I think I'll just move this logic from `config/netbox` to `addons_config/netbox`.

**Comment by saya6k** [comment]
I agree that using `/addons_config/netbox` would be better approach than using `/config/addon_configs/netbox`. Customizable directory can be advanced feature with `configuration.py`

**Comment by casperklein** [comment]
Custom netbox configurations can now be stored in `addon_configs/0da538cf_netbox` (https://github.com/casperklein/homeassistant-addons/commit/0bef2570145f4cc012a593b9e898ed650eb5eeab).
