### ISSUE TITLE
FR: make device-type-library-import as option

### ISSUE THREAD

**Issue by saya6k** [casperklein/homeassistant-addons#15]
**Add-on name**
Netbox

**Describe the feature you'd like**

Making device type in Netbox is often very time consuming. Netbox Community already supports [device-type-library-import](https://github.com/netbox-community/Device-Type-Library-Import) script that automatically update community-driven device types. I want to have this as an option.

It can default install all or no vendors depends on choice, but when vendors are defined, device type from specific vendors are installed.

**Describe alternatives you've considered**
Haven't thought about it.

**Additional context**
https://github.com/netbox-community/devicetype-library
https://github.com/netbox-community/Device-Type-Library-Import

**Comment by bertybuttface** [comment]
There is a plugin available that can do this:

https://github.com/Onemind-Services-LLC/netbox-metatype-importer

You can already add custom plugins to this addon, adding an example of how to use this plugin could close this issue?

**Comment by casperklein** [comment]
The above mentioned plugin works like charm:

<details>
<summary>configuration.py</summary>

```
PLUGINS = ['netbox_metatype_importer']

PLUGINS_CONFIG = {
    'netbox_metatype_importer': {
        'github_token': 'change-me'
    }
}
```

</details>

<details>
<summary>requirements.txt</summary>

```
netbox-metatype-importer
```

</details>

I think it's not worth to re-invent the wheel.
