### ISSUE TITLE
Netbox - Upgrade Debian 11 Bullseye (oldstable) to Debian 12 Bookworm (newstable)?

### ISSUE THREAD

**Issue by bertybuttface** [casperklein/homeassistant-addons#16]
Hello,

Is it worth bumping this from 11 to 12?

https://github.com/casperklein/homeassistant-addons/blob/f13efb5619d406e56758349b21165e638c71dd49/netbox/Dockerfile#L1

Cheers

**Comment by casperklein** [comment]
> Is it worth bumping this from 11 to 12?

Yes. But there is currently no need to rush. Debian 11 is fully supported. Currently the build fails with Debian 12. I will take a closer look when I have some spare time.

**Comment by casperklein** [comment]
Done in https://github.com/casperklein/homeassistant-addons/commit/aef9c576835d71d5221bfab2b759e19a038d3064 🎉
