### ISSUE TITLE
Netbox is not an option to install

### ISSUE THREAD

**Issue by commputethis** [casperklein/homeassistant-addons#17]
**Add-on name**
Netbox

**Describe the bug**
Netbox is not an option to add after adding the repository.  Only the 3 shown in the picture show up.

![image](https://github.com/casperklein/homeassistant-addons/assets/17625274/4af069ab-9152-46f9-938f-f2257f2ff4b6)

**To Reproduce**
1. It's probably somewhat obvious from the screenshot, but I added the repository 
![image](https://github.com/casperklein/homeassistant-addons/assets/17625274/e5130950-1f94-4f7f-b944-fa68a8a06e54)
2. I refreshed the add-on store page and only the 3 items showed up. (I also restarted home assistant with no change)

**Expected behavior**
Netbox should be an option to install.

**Screenshots**

**Additional context**

**Comment by commputethis** [comment]
I should have mentioned
![image](https://github.com/casperklein/homeassistant-addons/assets/17625274/dc51889a-de24-43ad-8b4a-f0cc07b0139c)

**Comment by commputethis** [comment]
I figured it out.  I needed to enable Advanced mode.  It is there now.

**Comment by casperklein** [comment]
Thank you for bringing that to my attention. I wasn't aware, that [marking](https://github.com/casperklein/homeassistant-addons/blob/251c0271d1010c8db308a01a7a0d4e597c83933c/netbox/config.json#L40) an addon as [experimental](https://developers.home-assistant.io/docs/add-ons/configuration#optional-configuration-options) will hide it, when advanced mode is not enabled in the user profile.
I'll remove this setting.
