### ISSUE TITLE
Can‘t open WebUI from Browser

### ISSUE THREAD

**Issue by superpower10** [casperklein/homeassistant-addons#19]
PI-Addon

Installed it and runs flawless.

I can open the WebUI from within Home Assistant but not in the Browser.

I left the UNPROTECTED web UI at Port 80 and 403 Forbidden. Tried Port 8181 - same.

Could someone please help?

**Comment by casperklein** [comment]
Adding `/admin` to the URL should work.

**Comment by superpower10** [comment]
Perfect. Works!

Thank you
