### ISSUE TITLE
Error when updating to version 3.1.10

### ISSUE THREAD

**Issue by ArtKZ** [casperklein/homeassistant-addons#4]
**Add-on name**
Netbox

**Describe the bug**
Error when updating to version 3.1.10
`Can't install casperklein/homeassistant-netbox:3.1.10: 404 Client Error for http+docker://localhost/v1.41/images/create?tag=3.1.10&fromImage=casperklein%2Fhomeassistant-netbox&platform=linux%2Famd64: Not Found ("manifest for casperklein/homeassistant-netbox:3.1.10 not found: manifest unknown: manifest unknown")`

**Comment by casperklein** [comment]
Please try again. Should be fixed now.

**Comment by ArtKZ** [comment]
Now the update is successful.
Thank you for your hard work!
