### ISSUE TITLE
Netbox plugins

### ISSUE THREAD

**Issue by akalagov** [casperklein/homeassistant-addons#6]
**Add-on name**
Netbox

**Describe the feature you'd like**
Ability to install plugins

**Additional context**
How do you feel about adding the ability to install plugins to the Netbox addon?

**Comment by casperklein** [comment]
Good idea, however I don't know a clever way to do so yet 😞

**Comment by akalagov** [comment]
From what I understand, the easiest way is to put the configuration.py and requirements.txt files in /config/netbox/... and copy them to /opt/netbox/... when loading the add-on.

**Comment by casperklein** [comment]
I've added plugin support for netbox. You can test it, by using this [repo](https://github.com/casperklein/homeassistant-addons-dev) and installing netbox-dev from there.

You have to create the directory `/config/netbox` and those two files: `configuration.py` and `requirements.txt`.

For example:

`/config/netbox/configuration.py`:

```
PLUGINS = ['netbox_dns','netbox_bgp','netbox_ipcalculator','netbox_qrcode']
```

`/config/netbox/requirements.txt`:

```
netbox-dns
netbox-bgp
netbox-ipcalculator
netbox-qrcode
```

Let me know, if that works for you.

**Comment by akalagov** [comment]
I checked - the plugins work. Thank you for your work!
When do you plan to merge with the main branch?

**Comment by casperklein** [comment]
When the next netbox version gets released.

**Comment by casperklein** [comment]
[Done](https://github.com/casperklein/homeassistant-addons/blob/master/netbox/CHANGELOG.md#338) 🎉

**Comment by casperklein** [comment]
@akalagov With the latest release, the location for custom configuration has [changed](https://github.com/casperklein/homeassistant-addons/tree/master/netbox#custom-netbox-configuration).
