### ISSUE TITLE
Please add a r/w mounted /share and /media directories to the Netbox plugin.

### ISSUE THREAD

**Issue by akalagov** [casperklein/homeassistant-addons#8]
**Add-on name**
Netbox

**Describe the feature you'd like**
Please add a r/w mounted /share and /media directories to the container. This will provide an option to change the storage location of some netbox and plugin files.

**Comment by casperklein** [comment]
Done: https://github.com/casperklein/homeassistant-addons/commit/b70aab399019939c5831958b2a530f1b1346062e

**Comment by akalagov** [comment]
Thank you for your work!
